-- Generated offline for review only; do not run on production.
BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0001_legacy_baseline

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    nombre TEXT NOT NULL, 
    correo TEXT NOT NULL, 
    contrasena TEXT NOT NULL, 
    plan TEXT NOT NULL, 
    activo INTEGER DEFAULT 1 NOT NULL, 
    plan_key TEXT DEFAULT '', 
    stripe_customer_id TEXT DEFAULT '', 
    stripe_subscription_id TEXT DEFAULT '', 
    subscription_status TEXT DEFAULT 'sin_pago', 
    creado TEXT DEFAULT '', 
    trial_end TEXT DEFAULT '', 
    email_verificado INTEGER DEFAULT 1 NOT NULL, 
    legal_accepted_at TEXT DEFAULT '', 
    trial_slot INTEGER DEFAULT 0 NOT NULL, 
    trial_queries_used INTEGER DEFAULT 0 NOT NULL, 
    CONSTRAINT pk_clientes PRIMARY KEY (id), 
    CONSTRAINT uq_clientes_correo UNIQUE (correo)
);

CREATE TABLE consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    empresa TEXT NOT NULL, 
    problema TEXT NOT NULL, 
    correo TEXT DEFAULT '', 
    respuesta TEXT DEFAULT '', 
    token TEXT DEFAULT '', 
    CONSTRAINT pk_consultas PRIMARY KEY (id)
);

CREATE TABLE rate_limits (
    clave TEXT NOT NULL, 
    inicio INTEGER NOT NULL, 
    intentos INTEGER DEFAULT 0 NOT NULL, 
    CONSTRAINT pk_rate_limits PRIMARY KEY (clave)
);

CREATE TABLE servicios_solicitados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    servicio_key TEXT NOT NULL, 
    servicio_nombre TEXT NOT NULL, 
    precio TEXT NOT NULL, 
    nombre TEXT NOT NULL, 
    empresa TEXT NOT NULL, 
    correo TEXT NOT NULL, 
    telefono TEXT DEFAULT '', 
    mensaje TEXT DEFAULT '', 
    estado TEXT DEFAULT 'Nueva' NOT NULL, 
    fecha TEXT NOT NULL, 
    CONSTRAINT pk_servicios_solicitados PRIMARY KEY (id)
);

CREATE TABLE stripe_webhook_events (
    event_id TEXT NOT NULL, 
    event_type TEXT NOT NULL, 
    processed_at TEXT NOT NULL, 
    CONSTRAINT pk_stripe_webhook_events PRIMARY KEY (event_id)
);

CREATE TABLE calendarios_contenido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    cliente_id BIGINT NOT NULL, 
    periodo TEXT NOT NULL, 
    contenido TEXT NOT NULL, 
    creado TEXT NOT NULL, 
    CONSTRAINT pk_calendarios_contenido PRIMARY KEY (id), 
    CONSTRAINT uq_calendarios_contenido_cliente_id UNIQUE (cliente_id, periodo), 
    CONSTRAINT fk_calendarios_contenido_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

CREATE TABLE citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    cliente_id BIGINT NOT NULL, 
    fecha TEXT NOT NULL, 
    hora TEXT NOT NULL, 
    modalidad TEXT NOT NULL, 
    motivo TEXT NOT NULL, 
    estado TEXT DEFAULT 'Pendiente', 
    CONSTRAINT pk_citas PRIMARY KEY (id), 
    CONSTRAINT fk_citas_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

CREATE TABLE diagnosticos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    cliente_id BIGINT NOT NULL, 
    web INTEGER DEFAULT 0 NOT NULL, 
    google INTEGER DEFAULT 0 NOT NULL, 
    redes INTEGER DEFAULT 0 NOT NULL, 
    resenas INTEGER DEFAULT 0 NOT NULL, 
    objetivos TEXT DEFAULT '', 
    puntuacion INTEGER DEFAULT 0 NOT NULL, 
    actualizado TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT pk_diagnosticos PRIMARY KEY (id), 
    CONSTRAINT uq_diagnosticos_cliente_id UNIQUE (cliente_id), 
    CONSTRAINT fk_diagnosticos_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

CREATE TABLE email_verifications (
    token TEXT NOT NULL, 
    cliente_id BIGINT NOT NULL, 
    expira TIMESTAMP WITH TIME ZONE NOT NULL, 
    usado INTEGER DEFAULT 0 NOT NULL, 
    CONSTRAINT pk_email_verifications PRIMARY KEY (token), 
    CONSTRAINT fk_email_verifications_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

CREATE TABLE estrategias_comerciales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    cliente_id BIGINT NOT NULL, 
    respuestas TEXT NOT NULL, 
    estrategia TEXT NOT NULL, 
    actualizado TEXT NOT NULL, 
    CONSTRAINT pk_estrategias_comerciales PRIMARY KEY (id), 
    CONSTRAINT uq_estrategias_comerciales_cliente_id UNIQUE (cliente_id), 
    CONSTRAINT fk_estrategias_comerciales_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

CREATE TABLE informes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    cliente_id BIGINT NOT NULL, 
    titulo TEXT NOT NULL, 
    contenido TEXT NOT NULL, 
    fecha TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT pk_informes PRIMARY KEY (id), 
    CONSTRAINT fk_informes_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

CREATE TABLE password_resets (
    token TEXT NOT NULL, 
    cliente_id BIGINT NOT NULL, 
    expira TIMESTAMP WITH TIME ZONE NOT NULL, 
    usado INTEGER DEFAULT 0 NOT NULL, 
    CONSTRAINT pk_password_resets PRIMARY KEY (token), 
    CONSTRAINT fk_password_resets_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

CREATE TABLE resultados_mensuales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    cliente_id BIGINT NOT NULL, 
    periodo TEXT NOT NULL, 
    contactos INTEGER DEFAULT 0 NOT NULL, 
    ventas INTEGER DEFAULT 0 NOT NULL, 
    ingresos FLOAT DEFAULT 0 NOT NULL, 
    resenas INTEGER DEFAULT 0 NOT NULL, 
    notas TEXT DEFAULT '', 
    informe TEXT NOT NULL, 
    creado TEXT NOT NULL, 
    CONSTRAINT pk_resultados_mensuales PRIMARY KEY (id), 
    CONSTRAINT uq_resultados_mensuales_cliente_id UNIQUE (cliente_id, periodo), 
    CONSTRAINT fk_resultados_mensuales_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

CREATE TABLE solicitudes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    cliente_id BIGINT NOT NULL, 
    asunto TEXT NOT NULL, 
    descripcion TEXT NOT NULL, 
    respuesta TEXT DEFAULT '', 
    estado TEXT DEFAULT 'Pendiente', 
    fecha TEXT DEFAULT '', 
    origen_respuesta TEXT DEFAULT 'automatizacion', 
    CONSTRAINT pk_solicitudes PRIMARY KEY (id), 
    CONSTRAINT fk_solicitudes_cliente_id_clientes FOREIGN KEY(cliente_id) REFERENCES clientes (id)
);

INSERT INTO alembic_version (version_num) VALUES ('0001_legacy_baseline') RETURNING alembic_version.version_num;

-- Running upgrade 0001_legacy_baseline -> 0002_saas_core

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    name TEXT NOT NULL, 
    slug VARCHAR(80) NOT NULL, 
    status VARCHAR(16) NOT NULL, 
    plan TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    legacy_cliente_id BIGINT NOT NULL, 
    CONSTRAINT pk_organizations PRIMARY KEY (id), 
    CONSTRAINT ck_organizations_status CHECK (status IN ('active','suspended','archived')), 
    CONSTRAINT ck_organizations_name CHECK (length(trim(name)) > 0), 
    CONSTRAINT ck_organizations_slug CHECK (slug=lower(slug) AND length(slug)>0), 
    CONSTRAINT uq_organizations_slug UNIQUE (slug), 
    CONSTRAINT uq_organizations_legacy_cliente_id UNIQUE (legacy_cliente_id), 
    CONSTRAINT fk_organizations_legacy_cliente_id_clientes FOREIGN KEY(legacy_cliente_id) REFERENCES clientes (id) ON DELETE RESTRICT, 
    CONSTRAINT ck_organizations_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    email VARCHAR(254) NOT NULL, 
    password_hash TEXT NOT NULL, 
    name TEXT NOT NULL, 
    status VARCHAR(16) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    last_login_at TIMESTAMP WITH TIME ZONE, 
    credential_version INTEGER DEFAULT 1 NOT NULL, 
    legacy_cliente_id BIGINT, 
    CONSTRAINT pk_users PRIMARY KEY (id), 
    CONSTRAINT ck_users_status CHECK (status IN ('active','suspended')), 
    CONSTRAINT ck_users_normalized_email CHECK (email=lower(trim(email)) AND length(email)>0), 
    CONSTRAINT ck_users_password_hash CHECK (length(password_hash)>0), 
    CONSTRAINT uq_users_email UNIQUE (email), 
    CONSTRAINT uq_users_legacy_cliente_id UNIQUE (legacy_cliente_id), 
    CONSTRAINT fk_users_legacy_cliente_id_clientes FOREIGN KEY(legacy_cliente_id) REFERENCES clientes (id) ON DELETE RESTRICT
);

CREATE TABLE organization_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    organization_id BIGINT NOT NULL, 
    user_id BIGINT NOT NULL, 
    role VARCHAR(16) NOT NULL, 
    status VARCHAR(16) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    CONSTRAINT pk_organization_memberships PRIMARY KEY (id), 
    CONSTRAINT uq_organization_memberships_organization_id UNIQUE (organization_id, user_id), 
    CONSTRAINT ck_organization_memberships_role CHECK (role IN ('owner','admin','manager','member','viewer')), 
    CONSTRAINT ck_organization_memberships_status CHECK (status IN ('active','revoked')), 
    CONSTRAINT fk_organization_memberships_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_organization_memberships_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX ix_memberships_organization ON organization_memberships (organization_id);

CREATE INDEX ix_memberships_user ON organization_memberships (user_id, status);

CREATE TABLE saas_migrations (
    version VARCHAR(80) NOT NULL, 
    enabled INTEGER NOT NULL, 
    applied_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    CONSTRAINT pk_saas_migrations PRIMARY KEY (version), 
    CONSTRAINT ck_saas_migrations_enabled CHECK (enabled IN (0,1))
);

CREATE TABLE saas_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    action TEXT NOT NULL, 
    organization_id BIGINT, 
    user_id BIGINT, 
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    CONSTRAINT pk_saas_audit PRIMARY KEY (id), 
    CONSTRAINT fk_saas_audit_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT, 
    CONSTRAINT fk_saas_audit_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX ix_audit_organization_created ON saas_audit (organization_id, created_at);

ALTER TABLE clientes ADD COLUMN organization_id BIGINT;

ALTER TABLE clientes ADD CONSTRAINT fk_clientes_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT;

CREATE INDEX ix_clientes_organization ON clientes (organization_id);

ALTER TABLE solicitudes ADD COLUMN organization_id BIGINT;

ALTER TABLE solicitudes ADD CONSTRAINT fk_solicitudes_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT;

CREATE INDEX ix_solicitudes_organization ON solicitudes (organization_id);

ALTER TABLE informes ADD COLUMN organization_id BIGINT;

ALTER TABLE informes ADD CONSTRAINT fk_informes_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT;

CREATE INDEX ix_informes_organization ON informes (organization_id);

ALTER TABLE citas ADD COLUMN organization_id BIGINT;

ALTER TABLE citas ADD CONSTRAINT fk_citas_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT;

CREATE INDEX ix_citas_organization ON citas (organization_id);

ALTER TABLE diagnosticos ADD COLUMN organization_id BIGINT;

ALTER TABLE diagnosticos ADD CONSTRAINT fk_diagnosticos_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT;

CREATE INDEX ix_diagnosticos_organization ON diagnosticos (organization_id);

ALTER TABLE estrategias_comerciales ADD COLUMN organization_id BIGINT;

ALTER TABLE estrategias_comerciales ADD CONSTRAINT fk_estrategias_comerciales_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT;

CREATE INDEX ix_estrategias_comerciales_organization ON estrategias_comerciales (organization_id);

ALTER TABLE calendarios_contenido ADD COLUMN organization_id BIGINT;

ALTER TABLE calendarios_contenido ADD CONSTRAINT fk_calendarios_contenido_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT;

CREATE INDEX ix_calendarios_contenido_organization ON calendarios_contenido (organization_id);

ALTER TABLE resultados_mensuales ADD COLUMN organization_id BIGINT;

ALTER TABLE resultados_mensuales ADD CONSTRAINT fk_resultados_mensuales_organization_id_organizations FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE RESTRICT;

CREATE INDEX ix_resultados_mensuales_organization ON resultados_mensuales (organization_id);

ALTER TABLE clientes ADD CONSTRAINT uq_clientes_organization_id_id UNIQUE (organization_id, id);

ALTER TABLE solicitudes ADD CONSTRAINT fk_solicitudes_tenant_account FOREIGN KEY(organization_id, cliente_id) REFERENCES clientes (organization_id, id) ON DELETE RESTRICT;

ALTER TABLE informes ADD CONSTRAINT fk_informes_tenant_account FOREIGN KEY(organization_id, cliente_id) REFERENCES clientes (organization_id, id) ON DELETE RESTRICT;

ALTER TABLE citas ADD CONSTRAINT fk_citas_tenant_account FOREIGN KEY(organization_id, cliente_id) REFERENCES clientes (organization_id, id) ON DELETE RESTRICT;

ALTER TABLE diagnosticos ADD CONSTRAINT fk_diagnosticos_tenant_account FOREIGN KEY(organization_id, cliente_id) REFERENCES clientes (organization_id, id) ON DELETE RESTRICT;

ALTER TABLE estrategias_comerciales ADD CONSTRAINT fk_estrategias_comerciales_tenant_account FOREIGN KEY(organization_id, cliente_id) REFERENCES clientes (organization_id, id) ON DELETE RESTRICT;

ALTER TABLE calendarios_contenido ADD CONSTRAINT fk_calendarios_contenido_tenant_account FOREIGN KEY(organization_id, cliente_id) REFERENCES clientes (organization_id, id) ON DELETE RESTRICT;

ALTER TABLE resultados_mensuales ADD CONSTRAINT fk_resultados_mensuales_tenant_account FOREIGN KEY(organization_id, cliente_id) REFERENCES clientes (organization_id, id) ON DELETE RESTRICT;

INSERT INTO saas_migrations(version,enabled,applied_at)
        VALUES('0001_saas_core',0,CURRENT_TIMESTAMP) ON CONFLICT(version) DO NOTHING;

INSERT INTO organizations(name,slug,status,plan,created_at,updated_at,legacy_cliente_id)
        SELECT nombre,'legacy-' || CAST(id AS TEXT),'active',COALESCE(NULLIF(plan_key,''),plan),
        CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,id FROM clientes c
        WHERE NOT EXISTS(SELECT 1 FROM organizations o WHERE o.legacy_cliente_id=c.id);

INSERT INTO users(email,password_hash,name,status,created_at,legacy_cliente_id)
        SELECT lower(trim(correo)),contrasena,nombre,'active',CURRENT_TIMESTAMP,id FROM clientes c
        WHERE NOT EXISTS(SELECT 1 FROM users u WHERE u.legacy_cliente_id=c.id)
        AND NOT EXISTS(SELECT 1 FROM organizations o JOIN organization_memberships m
          ON m.organization_id=o.id WHERE o.legacy_cliente_id=c.id);

INSERT INTO organization_memberships(organization_id,user_id,role,status,created_at)
        SELECT o.id,u.id,'owner','active',CURRENT_TIMESTAMP FROM organizations o
        JOIN users u ON u.legacy_cliente_id=o.legacy_cliente_id
        WHERE NOT EXISTS(SELECT 1 FROM organization_memberships m WHERE m.organization_id=o.id AND m.user_id=u.id);

UPDATE clientes SET organization_id=(SELECT id FROM organizations WHERE legacy_cliente_id=clientes.id) WHERE organization_id IS NULL;

UPDATE solicitudes SET organization_id=(SELECT organization_id FROM clientes WHERE id=solicitudes.cliente_id) WHERE organization_id IS NULL;

UPDATE informes SET organization_id=(SELECT organization_id FROM clientes WHERE id=informes.cliente_id) WHERE organization_id IS NULL;

UPDATE citas SET organization_id=(SELECT organization_id FROM clientes WHERE id=citas.cliente_id) WHERE organization_id IS NULL;

UPDATE diagnosticos SET organization_id=(SELECT organization_id FROM clientes WHERE id=diagnosticos.cliente_id) WHERE organization_id IS NULL;

UPDATE estrategias_comerciales SET organization_id=(SELECT organization_id FROM clientes WHERE id=estrategias_comerciales.cliente_id) WHERE organization_id IS NULL;

UPDATE calendarios_contenido SET organization_id=(SELECT organization_id FROM clientes WHERE id=calendarios_contenido.cliente_id) WHERE organization_id IS NULL;

UPDATE resultados_mensuales SET organization_id=(SELECT organization_id FROM clientes WHERE id=resultados_mensuales.cliente_id) WHERE organization_id IS NULL;

UPDATE saas_migrations SET enabled=1 WHERE version='0001_saas_core';

CREATE OR REPLACE FUNCTION inahi_tenant_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE tenant bigint;
    BEGIN
      IF NOT EXISTS(SELECT 1 FROM saas_migrations WHERE version='0001_saas_core' AND enabled=1) THEN RETURN NEW; END IF;
      SELECT organization_id INTO tenant FROM clientes WHERE id=NEW.cliente_id;
      IF TG_OP='INSERT' AND NEW.organization_id IS NULL THEN NEW.organization_id:=tenant; END IF;
      IF tenant IS NULL OR NEW.organization_id IS DISTINCT FROM tenant THEN RAISE EXCEPTION 'tenant mismatch'; END IF;
      IF TG_OP='UPDATE' AND NEW.cliente_id IS DISTINCT FROM OLD.cliente_id THEN RAISE EXCEPTION 'immutable tenant'; END IF;
      RETURN NEW;
    END; $$;

DROP TRIGGER IF EXISTS saas_solicitudes_guard ON solicitudes;

CREATE TRIGGER saas_solicitudes_guard BEFORE INSERT OR UPDATE ON solicitudes FOR EACH ROW EXECUTE FUNCTION inahi_tenant_guard();

DROP TRIGGER IF EXISTS saas_informes_guard ON informes;

CREATE TRIGGER saas_informes_guard BEFORE INSERT OR UPDATE ON informes FOR EACH ROW EXECUTE FUNCTION inahi_tenant_guard();

DROP TRIGGER IF EXISTS saas_citas_guard ON citas;

CREATE TRIGGER saas_citas_guard BEFORE INSERT OR UPDATE ON citas FOR EACH ROW EXECUTE FUNCTION inahi_tenant_guard();

DROP TRIGGER IF EXISTS saas_diagnosticos_guard ON diagnosticos;

CREATE TRIGGER saas_diagnosticos_guard BEFORE INSERT OR UPDATE ON diagnosticos FOR EACH ROW EXECUTE FUNCTION inahi_tenant_guard();

DROP TRIGGER IF EXISTS saas_estrategias_comerciales_guard ON estrategias_comerciales;

CREATE TRIGGER saas_estrategias_comerciales_guard BEFORE INSERT OR UPDATE ON estrategias_comerciales FOR EACH ROW EXECUTE FUNCTION inahi_tenant_guard();

DROP TRIGGER IF EXISTS saas_calendarios_contenido_guard ON calendarios_contenido;

CREATE TRIGGER saas_calendarios_contenido_guard BEFORE INSERT OR UPDATE ON calendarios_contenido FOR EACH ROW EXECUTE FUNCTION inahi_tenant_guard();

DROP TRIGGER IF EXISTS saas_resultados_mensuales_guard ON resultados_mensuales;

CREATE TRIGGER saas_resultados_mensuales_guard BEFORE INSERT OR UPDATE ON resultados_mensuales FOR EACH ROW EXECUTE FUNCTION inahi_tenant_guard();

CREATE OR REPLACE FUNCTION inahi_account_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF EXISTS(SELECT 1 FROM saas_migrations WHERE version='0001_saas_core' AND enabled=1) THEN
        IF TG_OP='INSERT' AND NEW.organization_id IS NOT NULL THEN RAISE EXCEPTION 'use enrollment'; END IF;
        IF TG_OP='UPDATE' AND NEW.organization_id IS DISTINCT FROM OLD.organization_id
          AND NEW.organization_id IS DISTINCT FROM (SELECT id FROM organizations WHERE legacy_cliente_id=NEW.id)
          THEN RAISE EXCEPTION 'tenant mismatch'; END IF;
      END IF;
      RETURN NEW;
    END; $$;

DROP TRIGGER IF EXISTS saas_account_guard ON clientes;

CREATE TRIGGER saas_account_guard BEFORE INSERT OR UPDATE ON clientes FOR EACH ROW EXECUTE FUNCTION inahi_account_guard();

CREATE OR REPLACE FUNCTION inahi_carrier_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.legacy_cliente_id IS DISTINCT FROM OLD.legacy_cliente_id THEN RAISE EXCEPTION 'immutable carrier'; END IF;
      RETURN NEW;
    END; $$;

DROP TRIGGER IF EXISTS saas_carrier_guard ON organizations;

CREATE TRIGGER saas_carrier_guard BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION inahi_carrier_guard();

CREATE OR REPLACE FUNCTION inahi_legacy_sync() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.correo IS DISTINCT FROM OLD.correo OR NEW.contrasena IS DISTINCT FROM OLD.contrasena THEN
        UPDATE users SET email=lower(trim(NEW.correo)),password_hash=NEW.contrasena,
          credential_version=credential_version+CASE WHEN password_hash<>NEW.contrasena THEN 1 ELSE 0 END
          WHERE legacy_cliente_id=NEW.id;
      END IF;
      IF NEW.nombre IS DISTINCT FROM OLD.nombre OR NEW.plan IS DISTINCT FROM OLD.plan OR NEW.plan_key IS DISTINCT FROM OLD.plan_key THEN
        UPDATE organizations SET name=NEW.nombre,plan=COALESCE(NULLIF(NEW.plan_key,''),NEW.plan),updated_at=CURRENT_TIMESTAMP WHERE legacy_cliente_id=NEW.id;
      END IF;
      RETURN NEW;
    END; $$;

DROP TRIGGER IF EXISTS saas_legacy_sync ON clientes;

CREATE TRIGGER saas_legacy_sync AFTER UPDATE ON clientes FOR EACH ROW EXECUTE FUNCTION inahi_legacy_sync();

UPDATE alembic_version SET version_num='0002_saas_core' WHERE alembic_version.version_num = '0001_legacy_baseline';

COMMIT;

